const MOVIES_LIST_REQUEST = 'MOVIES_LIST_REQUEST';
const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS';
const MOVIES_LIST_FAILURE = 'MOVIES_LIST_FAILURE';

const MOVIES_CREATE_REQUEST = 'MOVIES_CREATE_REQUEST';
const MOVIES_CREATE_SUCCESS = 'MOVIES_CREATE_SUCCESS';
const MOVIES_CREATE_FAILURE = 'MOVIES_CREATE_FAILURE';

const MOVIES_BY_ID_REQUEST = 'MOVIES_BY_ID_REQUEST';
const MOVIES_BY_ID_SUCCESS = 'MOVIES_BY_ID_SUCCESS';
const MOVIES_BY_ID_FAILURE = 'MOVIES_BY_ID_FAILURE';

const MOVIES_DELETE_BY_ID_REQUEST = 'MOVIES_DELETE_BY_ID_REQUEST';
const MOVIES_DELETE_BY_ID_SUCCESS = 'MOVIES_DELETE_BY_ID_SUCCESS';
const MOVIES_DELETE_BY_ID_FAILURE = 'MOVIES_DELETE_BY_ID_FAILURE';

const MOVIES_EDIT_BY_ID_REQUEST = 'MOVIES_EDIT_BY_ID_REQUEST';
const MOVIES_EDIT_BY_ID_SUCCESS = 'MOVIES_EDIT_BY_ID_SUCCESS';
const MOVIES_EDIT_BY_ID_FAILURE = 'MOVIES_EDIT_BY_ID_FAILURE';

const MOVIES_CHANGE_DIR_REQUEST = 'MOVIES_CHANGE_DIR_REQUEST';
const MOVIES_CHANGE_DIR_SUCCESS = 'MOVIES_CHANGE_DIR_SUCCESS';
const MOVIES_CHANGE_DIR_FAILURE = 'MOVIES_CHANGE_DIR_FAILURE';



const types = {
    MOVIES_LIST_FAILURE,
    MOVIES_LIST_REQUEST,
    MOVIES_LIST_SUCCESS,
    MOVIES_CREATE_FAILURE,
    MOVIES_CREATE_REQUEST,
    MOVIES_CREATE_SUCCESS,
    MOVIES_BY_ID_FAILURE,
    MOVIES_BY_ID_REQUEST,
    MOVIES_BY_ID_SUCCESS,
    MOVIES_DELETE_BY_ID_FAILURE,
    MOVIES_DELETE_BY_ID_REQUEST,
    MOVIES_DELETE_BY_ID_SUCCESS,
    MOVIES_EDIT_BY_ID_FAILURE,
    MOVIES_EDIT_BY_ID_REQUEST,
    MOVIES_EDIT_BY_ID_SUCCESS,
    MOVIES_CHANGE_DIR_FAILURE,
    MOVIES_CHANGE_DIR_REQUEST,
    MOVIES_CHANGE_DIR_SUCCESS,
}

export default types;