const ACTORS_LIST_REQUEST = 'ACTORS_LIST_REQUEST';
const ACTORS_LIST_SUCCESS = 'ACTORS_LIST_SUCCESS';
const ACTORS_LIST_FAILURE = 'ACTORS_LIST_FAILURE';

const ACTORS_ADD_ACTOR_REQUEST = 'ACTORS_ADD_ACTOR_REQUEST';
const ACTORS_ADD_ACTOR_SUCCESS = 'ACTORS_ADD_ACTOR_SUCCESS';
const ACTORS_ADD_ACTOR_FAILURE = 'ACTORS_ADD_ACTOR_FAILURE';

const ACTORS_ACTOR_DEL_REQUEST = 'ACTORS_ACTOR_DEL_REQUEST';
const ACTORS_ACTOR_DEL_SUCCESS = 'ACTORS_ACTOR_DEL_SUCCESS';
const ACTORS_ACTOR_DEL_FAILURE = 'ACTORS_ACTOR_DEL_FAILURE';

const types = {
    ACTORS_LIST_FAILURE,
    ACTORS_LIST_REQUEST,
    ACTORS_LIST_SUCCESS,
    ACTORS_ADD_ACTOR_FAILURE,
    ACTORS_ADD_ACTOR_REQUEST,
    ACTORS_ADD_ACTOR_SUCCESS,
    ACTORS_ACTOR_DEL_FAILURE,
    ACTORS_ACTOR_DEL_REQUEST,
    ACTORS_ACTOR_DEL_SUCCESS
}

export default types;