const PEOPLE_LIST_REQUEST = 'PEOPLE_LIST_REQUEST';
const PEOPLE_LIST_SUCCESS = 'PEOPLE_LIST_SUCCESS';
const PEOPLE_LIST_FAILURE = 'PEOPLE_LIST_FAILURE';

const PEOPLE_CREATE_REQUEST = 'PEOPLE_CREATE_REQUEST';
const PEOPLE_CREATE_SUCCESS = 'PEOPLE_CREATE_SUCCESS';
const PEOPLE_CREATE_FAILURE = 'PEOPLE_CREATE_FAILURE';

const PEOPLE_DELETE_BY_ID_REQUEST = 'PEOPLE_DELETE_BY_ID_REQUEST';
const PEOPLE_DELETE_BY_ID_SUCCESS = 'PEOPLE_DELETE_BY_ID_SUCCESS';
const PEOPLE_DELETE_BY_ID_FAILURE = 'PEOPLE_DELETE_BY_ID_FAILURE';

const PEOPLE_EDIT_BY_ID_REQUEST = 'PEOPLE_EDIT_BY_ID_REQUEST';
const PEOPLE_EDIT_BY_ID_SUCCESS = 'PEOPLE_EDIT_BY_ID_SUCCESS';
const PEOPLE_EDIT_BY_ID_FAILURE = 'PEOPLE_EDIT_BY_ID_FAILURE';

const PEOPLE_FETCH_BY_ID_REQUEST = 'PEOPLE_FETCH_BY_ID_REQUEST';
const PEOPLE_FETCH_BY_ID_SUCCESS = 'PEOPLE_FETCH_BY_ID_SUCCESS';
const PEOPLE_FETCH_BY_ID_FAILURE = 'PEOPLE_FETCH_BY_ID_FAILURE';



const types = {
    PEOPLE_LIST_FAILURE,
    PEOPLE_LIST_REQUEST,
    PEOPLE_LIST_SUCCESS,
    PEOPLE_CREATE_FAILURE,
    PEOPLE_CREATE_REQUEST,
    PEOPLE_CREATE_SUCCESS,
    PEOPLE_FETCH_BY_ID_FAILURE,
    PEOPLE_FETCH_BY_ID_REQUEST,
    PEOPLE_FETCH_BY_ID_SUCCESS,
    PEOPLE_DELETE_BY_ID_FAILURE,
    PEOPLE_DELETE_BY_ID_REQUEST,
    PEOPLE_DELETE_BY_ID_SUCCESS,
    PEOPLE_EDIT_BY_ID_FAILURE,
    PEOPLE_EDIT_BY_ID_REQUEST,
    PEOPLE_EDIT_BY_ID_SUCCESS,
}

export default types;